export { default as ArrowUpIcon } from './arrowUp.svg'
export { default as ArrowDownIcon } from './arrowDown.svg'
export { default as CodeIcon } from './code.svg'
export { default as CopyIcon } from './copy.svg'
export { default as PlayIcon } from './play.svg'
export { default as QuestionIcon } from './question.svg'
export { default as ClockIcon } from './clock.svg'
export { default as ContestIcon } from './chart.svg'
