export { default as DashIcon } from './dashboard.svg'
export { default as BulbIcon } from './bulb.svg'
export { default as GroupIcon } from './userGroup.svg'
export { default as ClipboardIcon } from './clipboard.svg'
export { default as ContestIcon } from './chart.svg'
export { default as StarIcon } from './star.svg'
